# Generated by Django 4.2 on 2025-05-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("koumaglo_parametres", "0001_initial"),
        ("koumaglo_medecins", "0001_initial"),
        ("koumaglo_consultations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_facture", models.CharField(max_length=50, unique=True)),
                ("type_facture", models.CharField(max_length=50)),
                ("date_enreg_facture", models.DateTimeField(auto_now_add=True)),
                ("date_paiement_facture", models.DateTimeField(blank=True, null=True)),
                (
                    "montant_facture",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "montant_paye_facture",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures",
                        to="koumaglo_consultations.consultation",
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="koumaglo_medecins.medecin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paymentDate", models.DateTimeField()),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="koumaglo_factures.facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
            },
        ),
        migrations.CreateModel(
            name="FactureDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_detail_facture", models.CharField(max_length=50, unique=True)),
                (
                    "montant_facture_detail",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="koumaglo_parametres.acte",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="koumaglo_factures.facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail Facture",
                "verbose_name_plural": "Détails Factures",
            },
        ),
    ]
