# Generated by Django 4.2 on 2025-05-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                (
                    "civilite",
                    models.CharField(
                        choices=[
                            ("M", "Monsieur"),
                            ("Mme", "Madame"),
                            ("Mlle", "Mademoiselle"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Personne",
                "verbose_name_plural": "Personnes",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "personne",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="koumaglo_patients.personne",
                    ),
                ),
                ("date_enreg", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
    ]
