# Generated by Django 4.2 on 2025-05-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("koumaglo_patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffecterSpecialite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_affectation", models.DateField()),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Affectation Spécialité",
                "verbose_name_plural": "Affectations Spécialités",
            },
        ),
        migrations.CreateModel(
            name="Specialite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("libelle", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Spécialité",
                "verbose_name_plural": "Spécialités",
            },
        ),
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "personne",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="koumaglo_patients.personne",
                    ),
                ),
                ("titre_medecin", models.CharField(max_length=50)),
                (
                    "specialites",
                    models.ManyToManyField(
                        through="koumaglo_medecins.AffecterSpecialite",
                        to="koumaglo_medecins.specialite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Médecin",
                "verbose_name_plural": "Médecins",
            },
        ),
        migrations.AddField(
            model_name="affecterspecialite",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="koumaglo_medecins.medecin",
            ),
        ),
        migrations.AddField(
            model_name="affecterspecialite",
            name="specialite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="koumaglo_medecins.specialite",
            ),
        ),
    ]
