# Generated by Django 4.2 on 2025-05-06 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_medicament", models.CharField(max_length=50, unique=True)),
                ("libelle_medicament", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Médicament",
                "verbose_name_plural": "Médicaments",
                "ordering": ["libelle_medicament"],
            },
        ),
        migrations.CreateModel(
            name="TypeActe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("libelle", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "montant_defaut",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type d'acte",
                "verbose_name_plural": "Types d'actes",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="Acte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_acte", models.CharField(max_length=50, unique=True)),
                ("libelle_acte", models.CharField(max_length=100)),
                ("montant_acte", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actes",
                        to="koumaglo_parametres.typeacte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acte",
                "verbose_name_plural": "Actes",
            },
        ),
    ]
