# Generated by Django 4.2 on 2025-05-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("koumaglo_medecins", "0001_initial"),
        ("koumaglo_consultations", "0002_initial"),
        ("koumaglo_parametres", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typeacte",
            name="montant_defaut",
        ),
        migrations.AddField(
            model_name="acte",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actes",
                to="koumaglo_consultations.consultation",
            ),
        ),
        migrations.AddField(
            model_name="typeacte",
            name="specialites",
            field=models.ManyToManyField(
                blank=True,
                related_name="types_actes",
                to="koumaglo_medecins.specialite",
            ),
        ),
    ]
