# Generated by Django 4.2 on 2025-05-08 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("koumaglo_medecins", "0001_initial"),
        (
            "koumaglo_parametres",
            "0002_remove_typeacte_montant_defaut_acte_consultation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typeacte",
            name="specialites",
        ),
        migrations.AddField(
            model_name="acte",
            name="specialite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actes",
                to="koumaglo_medecins.specialite",
            ),
        ),
    ]
